import routes from './routes.json'

/**
 * Return the uri based on the route name
 *
 * Use json file generated by command :
 *
 * php artisan happy:route
 *
 * @param string routename (ex: user.update)
 * @param object optional parameters (ex: {user : 1})
 *
 * @return string ex (route('user.update', {user : 1}) : /api/user/1)
 */
export default (routename, parameters = {}) => {
    let uri = routes[routename];

    if (uri === undefined) {
        console.error('Cannot find route:', routename);
        return console.table(routes);
    }

    // replace parameters on uri
    Object.keys(parameters)
          .forEach(key => uri = uri.replace(new RegExp('{' + key + '\\??}'), parameters[key]));

    // finally, remove any leftover optional parameters (inc leading slash)
    return uri.replace(/\/{[a-zA-Z]+\?}/, '');
}
